version: "{build}"

cache:
 - C:\gopath\pkg\mod -> go.sum
 - C:\Users\appveyor\AppData\Local\Temp\chocolatey\ -> appveyor.yml

clone_folder: C:\gopath\src\github.com\influxdata\telegraf

environment:
  GOPATH: C:\gopath
  GOVERSION: 1.12.7
  GO111MODULE: 'on'

platform: x64

install:
  - IF EXIST "C:\Go" rmdir /S /Q C:\Go
  - choco install golang --version "%GOVERSION%"
  - choco install make
  - cd "%GOPATH%\src\github.com\influxdata\telegraf"
  - git config --system core.longpaths true
  - go version
  - go env

build_script:
  - make
  - go mod verify

test_script:
  - make check
  - make test-windows

artifacts:
  - path: telegraf.exe
