---
defaults:
  defaults: &defaults
    working_directory: '/go/src/github.com/influxdata/telegraf'
  go-1_11: &go-1_11
    docker:
      - image: 'quay.io/influxdb/telegraf-ci:1.11.10'
        environment:
          GO111MODULE: 'on'
  go-1_12: &go-1_12
    docker:
      - image: 'quay.io/influxdb/telegraf-ci:1.12.5'
        environment:
          GO111MODULE: 'on'

version: 2
jobs:
  deps:
    <<: [ *defaults, *go-1_12 ]
    steps:
      - checkout
      - restore_cache:
          key: go-mod-v1-{{ checksum "go.sum" }}
      - run: 'make deps'
      - run: 'go mod verify'
      - save_cache:
          name: 'go module cache'
          key: go-mod-v1-{{ checksum "go.sum" }}
          paths:
            - '/go/pkg/mod'
      - persist_to_workspace:
          root: '/go'
          paths:
            - '*'

  test-go-1.11:
    <<: [ *defaults, *go-1_11 ]
    steps:
      - attach_workspace:
          at: '/go'
      - run: 'make check'
      - run: 'make test'
  test-go-1.12:
    <<: [ *defaults, *go-1_12 ]
    steps:
      - attach_workspace:
          at: '/go'
      - run: 'GOARCH=386 make check'
      - run: 'GOARCH=386 make test'
  test-go-1.12-386:
    <<: [ *defaults, *go-1_12 ]
    steps:
      - attach_workspace:
          at: '/go'
      - run: 'GOARCH=386 make check'
      - run: 'GOARCH=386 make test'

  package:
    <<: [ *defaults, *go-1_12 ]
    steps:
      - attach_workspace:
          at: '/go'
      - run: 'make package'
      - store_artifacts:
          path: './build'
          destination: 'build'
  release:
    <<: [ *defaults, *go-1_12 ]
    steps:
      - attach_workspace:
          at: '/go'
      - run: 'make package-release'
      - store_artifacts:
          path: './build'
          destination: 'build'
  nightly:
    <<: [ *defaults, *go-1_12 ]
    steps:
      - attach_workspace:
          at: '/go'
      - run: 'make package-nightly'
      - store_artifacts:
          path: './build'
          destination: 'build'

workflows:
  version: 2
  check:
    jobs:
      - 'deps':
          filters:
            tags:
              only: /.*/
      - 'test-go-1.11':
          requires:
            - 'deps'
          filters:
            tags:
              only: /.*/
      - 'test-go-1.12':
          requires:
            - 'deps'
          filters:
            tags:
              only: /.*/
      - 'test-go-1.12-386':
          requires:
            - 'deps'
          filters:
            tags:
              only: /.*/
      - 'package':
          requires:
            - 'test-go-1.11'
            - 'test-go-1.12'
            - 'test-go-1.12-386'
      - 'release':
          requires:
            - 'test-go-1.11'
            - 'test-go-1.12'
            - 'test-go-1.12-386'
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
  nightly:
    jobs:
      - 'deps'
      - 'test-go-1.11':
          requires:
            - 'deps'
      - 'test-go-1.12':
          requires:
            - 'deps'
      - 'test-go-1.12-386':
          requires:
            - 'deps'
      - 'nightly':
          requires:
            - 'test-go-1.11'
            - 'test-go-1.12'
            - 'test-go-1.12-386'
    triggers:
      - schedule:
          cron: "0 7 * * *"
          filters:
            branches:
              only:
                - master
